"""Add orders table

Revision ID: 16000ceb044a
Revises: 0002_add_policy_discrepancy
Create Date: 2026-02-03 13:46:52.949739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16000ceb044a'
down_revision = '0002_add_policy_discrepancy'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###