"""empty message

Revision ID: 19e8a9e9cc41
Revises: 16000ceb044a
Create Date: 2026-02-03 15:27:19.404446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19e8a9e9cc41'
down_revision = '16000ceb044a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###