"""Add warehouse and stock logic

Revision ID: b5085c35fa71
Revises: 19e8a9e9cc41
Create Date: 2026-02-04 13:44:12.930287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5085c35fa71'
down_revision = '19e8a9e9cc41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('stock', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'stock')
    # ### end Alembic commands ###